name: Nota Bene
favicon: null
layout_spectrum: 0.14555789856240153
typography_spectrum: 0.5928584358189255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12069883802905679
  lightness: 0.33040537941269577
  saturation: 0.11923498380929232
  rhythmicContrast: 0.8470735398586839
purpose: []
